# Default values for prom2icm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: liftracr.azurecr.io/artifact/c6ca85d0-80f3-49b5-b6c0-da1de7dbfc6f/buddy/prom2icm
  pullPolicy: IfNotPresent
  tag: "1.2201.01891.2844-6d1b2e1b"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

icm:
  connectorEndpoint: https://prod.microsofticm.com/Connector3/ConnectorIncidentManager.svc
  # certificateKeyVault: https://lmdfda200901wuskv.vault.azure.net/
  certificateName: icm-cert # name of the key vault certificate for icm connector
  # connectorId: 2bb00c56-1a2d-477b-9b02-05562eb1f8b2 # https://portal.microsofticm.com/imp/v3/administration/connectoronboarding​
  # notificatEmail: random@microsoft.com

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
