azureIdentity:
  enabled: true # enabled/disable deployment of azure identity and binding
  name: "azure-identity"
  type: 0 # type 0: MSI, type 1: Service Principal
  resourceID: /subscriptions/73543923-8c67-42cf-b9b2-cb816bb61581/resourceGroups/aksgenevatest/providers/Microsoft.ManagedIdentity/userAssignedIdentities/podidentity
  clientID: "dcf88038-3699-4ddb-b660-cd4279dd347c"

azureIdentityBinding:
  name: "azure-identity-binding"
  selector: liftr-aad-pod-identity