apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-mock-server-svc
    namespace: {{ .Release.Namespace }}
    labels:
      app.kubernetes.io/managed-by: helm
spec:
    ports:
        - port: 80
          protocol: TCP
          targetPort: 8080
    selector:
        app: {{ .Release.Name }}-mock-server
    type: ClusterIP
