---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-liftr-sample-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-liftr-sample-worker
    app.kubernetes.io/name: liftr-sample-worker
    app.kubernetes.io/managed-by: helm
    appVersion: {{ required "The appVersion must be provided." .Values.appVersion }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-liftr-sample-worker
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-liftr-sample-worker
        aadpodidbinding: liftr-aad-pod-identity
        appVersion: {{ .Values.appVersion }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: liftr-sample-worker-container
        image: {{ required "The imageRegistry parameter must be provided." .Values.imageRegistry }}/{{ required "The sampleWorker.imageName parameter must be provided." .Values.sampleWorker.imageName }}
        ports:
          - containerPort: 5000
        env:
          - name: VaultEndpoint
            value: {{ required "The Key Vault endpoint for the app to load secrets must be provided." .Values.vaultEndpoint }}
          - name: DOTNET_ENVIRONMENT
            value: {{ required "The APP_ASPNETCORE_ENVIRONMENT must be provided." .Values.APP_ASPNETCORE_ENVIRONMENT }}