# Default values for geneva.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

linuxgenevaACR:
  endpoint: linuxgeneva-microsoft.azurecr.io

# The version are referenced at three places. You need to update all of them. Please search for this sentence.
# Latest geneva image versions: https://genevamondocs.azurewebsites.net/collect/environments/linuxcontainers.html
mdsd:
  dockerTag: master_246

mdm:
  dockerTag: master_28

fluentd:
  dockerTag: master_124

secpack:
  dockerTag: master_30

promMdmConverter:
  name: prom-mdm-converter
  promConverterImagePullPolicy:
  image:
    name: shared/prom-mdm-converter
    tag: 2.0.master.20200106.5

  metrics: # Metrics below with a suffix "_named" or "_rate" are likely defined in the Prometheus configuration
    kube_pod_status_phase:
    kube_pod_container_status_running:
    kubelet_running_pod_count_named:
    kubelet_running_container_count_named:
    container_memory_usage_bytes:
    node_cpu_usage:
    node_memory_MemAvailable_bytes_named:
    node_memory_Active_bytes_named:
    kube_node_status_condition:
    node_filesystem_avail_bytes_named:
    node_network_receive_bytes_total_rate:
    node_network_receive_drop_total_rate:
    node_network_transmit_bytes_total_rate:
    node_network_transmit_drop_total_rate:

prometheus:
  rbac:
    create: false
  serviceAccounts:
    alertmanager:
      create: false
    pushgateway:
      create: false
    kubeStateMetrics:
      create: false
    nodeExporter:
      create: false
    server:
      create: false
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  server:
    persistentVolume:
      size: 32Gi
    retention: 12h
  serverFiles:
    prometheus.yml:
      remote_write:
        - url: "http://prom-mdm-converter/receive"
    rules:
      groups:
        - name: mdm_counter_conversions
          interval: 1m
          rules: # How to identify metrics to collect https://msazure.visualstudio.com/KubernetesSharedTools/_git/prom-mdm-converter?path=%2Fcharts%2Fprom-mdm-converter%2FREADME.md&version=GBmaster&_a=preview
            - record: node_cpu_usage
              expr: 100 - (avg by (nodename) (irate(node_cpu_seconds_total{mode="idle"}[5m]) * on(instance) group_left(nodename) node_uname_info * 100))- (avg by (nodename) (irate(node_cpu_seconds_total{mode="iowait"}[5m]) * on(instance) group_left(nodename) node_uname_info * 100))
            - record: node_network_receive_bytes_total_rate
              expr: sum by (nodename) (irate(node_network_receive_bytes_total{device="eth0"}[5m]) * 60 * on(instance) group_left(nodename) node_uname_info)
            - record: node_network_receive_drop_total_rate
              expr: sum by (nodename) (irate(node_network_receive_drop_total{device="eth0"}[5m]) * 60 * on(instance) group_left(nodename) node_uname_info)
            - record: node_network_transmit_bytes_total_rate
              expr: sum by (nodename) (irate(node_network_transmit_bytes_total{device="eth0"}[5m]) * 60 * on(instance) group_left(nodename) node_uname_info)
            - record: node_network_transmit_drop_total_rate
              expr: sum by (nodename) (irate(node_network_transmit_drop_total{device="eth0"}[5m]) * 60 * on(instance) group_left(nodename) node_uname_info)
            - record: kubelet_running_container_count_named
              expr: label_join(kubelet_running_container_count, "nodename", "", "instance")
            - record: kubelet_running_pod_count_named
              expr: label_join(kubelet_running_pod_count, "nodename", "", "instance")
            - record: node_filesystem_avail_bytes_named
              expr: node_filesystem_avail_bytes * on(instance) group_left(nodename) node_uname_info
            - record: node_memory_MemAvailable_bytes_named
              expr: node_memory_MemAvailable_bytes * on(instance) group_left(nodename) node_uname_info
            - record: node_memory_Active_bytes_named
              expr: node_memory_Active_bytes * on(instance) group_left(nodename) node_uname_info
