# Default values for geneva.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

linuxgenevaACR:
  endpoint: linuxgeneva-microsoft.azurecr.io

# [[[GENEVA_UPDATE_CHANGE_HERE]]]
# The version are referenced at three places. You need to update all of them. Please search for this sentence.
# Latest geneva image versions: https://genevamondocs.azurewebsites.net/collect/references/linuxcontainers.html
# latest prom mdm image version: https://msazure.visualstudio.com/Liftr/_build?definitionId=113171&_a=summary&view=runs
mdsd:
  dockerTag: master_20211223.1
mdm:
  dockerTag: master_20220111.2

fluentd:
  dockerTag: master_20220121.1

secpack:
  dockerTag: master_20211102.2

promMdmConverter:
  name: prom-mdm-converter
  replicas: 1
  promConverterImagePullPolicy: Always
  dockerTag: 2.0.master.20211213.1

  metrics: # Metrics below with a suffix "_named" or "_rate" are likely defined in the Prometheus configuration
    kube_pod_status_phase:
    kube_pod_container_status_running:
    kubelet_running_pod_count_named:
    kubelet_running_container_count_named:
    container_memory_usage_bytes:
    node_cpu_usage:
    node_memory_MemAvailable_bytes_named:
    node_memory_Active_bytes_named:
    kube_node_status_condition:
    node_filesystem_avail_bytes_named:
    node_network_receive_bytes_total_rate:
    node_network_receive_drop_total_rate:
    node_network_transmit_bytes_total_rate:
    node_network_transmit_drop_total_rate:
