apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: mdm-secret-provider
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: {{ required "Certificate key vault name mush be provided." .Values.keyvault }}
    tenantId: {{ required "Certificate key vault tenant Id must be provided." .Values.tenantId }}
    # Note: For chain of certificates, using object type cert only returns the Server certificate and not the entire chain.
    objects: |
      array:
        - |
          objectName: GenevaClientCert
          objectType: secret
          objectAlias: mdm-key.pem
          objectVersion: ""
        - |
          objectName: GenevaClientCert
          objectType: cert
          objectAlias: mdm-cert.pem
          objectVersion: ""
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azsecpack-secret-provider
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: {{ required "Certificate key vault name mush be provided." .Values.keyvault }}
    tenantId: {{ required "Certificate key vault tenant Id must be provided." .Values.tenantId }}
    objects: |
      array:
        - |
          objectName: GenevaClientCert
          objectType: secret
          objectAlias: azsecpack-key.pem
          objectVersion: ""
        - |
          objectName: GenevaClientCert
          objectType: cert
          objectAlias: azsecpack-cert.pem
          objectVersion: ""
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: mdsd-secret-provider
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: {{ required "Certificate key vault name mush be provided." .Values.keyvault }}
    tenantId: {{ required "Certificate key vault tenant Id must be provided." .Values.tenantId }}
    objects:  |
      array:
        - |
          objectName: GenevaClientCert
          objectAlias: geneva_cert.pem
          objectType: secret
---
#This is temporary as MDSD at startup looks for certs at /geneva/geneva_auth directory,
#this cert is not used for actual auth. Legacy way of mounting should be removed once 
#the geneva team fixes this behaviour.
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: mdsd-legacy-secret-provider
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: {{ required "Certificate key vault name mush be provided." .Values.keyvault }}
    tenantId: {{ required "Certificate key vault tenant Id must be provided." .Values.tenantId }}
    objects: |
      array:
        - |
          objectName: GenevaClientCert
          objectType: secret
          objectAlias: gcskey.pem
          objectVersion: ""
        - |
          objectName: GenevaClientCert
          objectType: cert
          objectAlias: gcscert.pem
          objectVersion: ""