#################################################################################
#                      OneBranch Pipelines - PR Build                           #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

trigger: # https://aka.ms/obpipelines/triggers
  branches:
    include:
      - master

parameters: # parameters are shown up in ADO UI in a build queue time
  - name: "debug"
    displayName: "Enable debug output"
    type: boolean
    default: true

variables:
  CDP_DEFINITION_BUILD_COUNT: $[counter('', 0)] # needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning
  system.debug: ${{ parameters.debug }}

  MajorVersion: 3
  MinorVersion: 2203

  LinuxContainerImage: "onebranch.azurecr.io/linux/ubuntu-1804:latest" # Docker image which is used to build the project https://aka.ms/obpipelines/containers

  enablingSigning: true

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates # https://aka.ms/obpipelines/templates
  parameters:
    globalSdl:
      binskim:
        enabled: true
        analyzeTargetGlob: "**/Microsoft.Liftr.*.dll"
      eslint:
        enabled: false
      cg:
        failOnAlert: true
      credscan:
        enabled: true
        suppressionsFile: $(Build.SourcesDirectory)/.config/CredScanSuppressions.json
      sbom:
        enabled: true
      tsa:
        enabled: false
      perStage:
        sdl_sources:
          checkout_all_repos: true

    stages:
      - template: /.pipelines/OneBranch.Linux.yml@self
