# We need a separate ingress for the TM liveness ping. This one is not restricted to any host.
# The TM ping traffic is pinging an IP instead of a host. Hence cannot be using the other one.
# also, the other ingress will block '/metrics' which is outside of '/api/liveness-probe'.
# Hence cannot be specified in one ingress.
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-gateway-web-tm-ping-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: helm
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/rewrite-target https://kubernetes.github.io/ingress-nginx/examples/rewrite/

spec:
  rules:
    - http:
        paths:
          - path: /api/liveness-probe
            backend:
              serviceName: {{ .Release.Name }}-gateway-web-svc
              servicePort: 80

  # This section is only required if TLS is to be enabled for the Ingress
  tls:
      - hosts:
          - {{ required "The hostname must be provided." .Values.hostname }}
          - {{ required "The aksdomain must be provided." .Values.aksdomain }}
        secretName: {{ .Release.Name }}-gateway-tls