apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-tls-secret-provider
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: {{ required "TLS cert key vault name mush be provided." .Values.keyvault }}
    tenantId: {{ required "TLS cert key vault tenant Id must be provided." .Values.tenantId }}
    # Note: For chain of certificates, using object type cert only returns the Server certificate and not the entire chain.
    objects:  |
      array:
        - |
          objectName: ssl-cert
          objectType: secret
  secretObjects:
    - secretName: {{ .Release.Name }}-gateway-tls
      type: kubernetes.io/tls
      data:
      - objectName: ssl-cert
        key: tls.key
      - objectName: ssl-cert
        key: tls.crt