---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-tls-secret
type: kubernetes.io/tls
data:
  tls.crt: {{ required "TLS cert must be provided." .Values.sslcertb64 }}
  tls.key: {{ required "TLS key must be provided." .Values.sslkeyb64 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liftr-gateway-web
  labels:
    app: liftr-gateway-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: liftr-gateway-web
  template:
    metadata:
      labels:
        app: liftr-gateway-web
        aadpodidbinding: liftr-aad-pod-identity
    spec:
      containers:
      - name: liftr-gateway-web-container
        image: {{ required "The imageRegistry parameter must be provided." .Values.imageRegistry }}/{{ required "The gatewayWeb.imageName parameter must be provided." .Values.gatewayWeb.imageName }}
        ports:
          - containerPort: 5000
        env:
          - name: STATSD_HOST
            value: geneva-services
          - name: VaultEndpoint
            value: {{ required "The Key Vault endpoint for the app to load secrets must be provided." .Values.vaultEndpoint }}
          - name: ASPNETCORE_ENVIRONMENT
            value: {{ required "The APP_ASPNETCORE_ENVIRONMENT must be provided." .Values.APP_ASPNETCORE_ENVIRONMENT }}
---
apiVersion: v1
kind: Service
metadata:
    name: "liftr-gateway-web-svc"
spec:
    ports:
        - port: 80
          protocol: TCP
          targetPort: 5000
    selector:
        app: liftr-gateway-web
    type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: liftr-gateway-web-ingress
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host:  {{ required "The hostname must be provided." .Values.hostname }}
      http:
          paths:
          - backend:
              serviceName: "liftr-gateway-web-svc"
              servicePort: 80
            path: /
  # This section is only required if TLS is to be enabled for the Ingress
  tls:
      - hosts:
          - {{ required "The hostname must be provided." .Values.hostname }}
        secretName: ingress-tls-secret