---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-tls-secret
type: kubernetes.io/tls
data:
  tls.crt: {{ required "TLS cert must be provided." .Values.sslcertb64 }}
  tls.key: {{ required "TLS key must be provided." .Values.sslkeyb64 }}
---
# The ConfigMap API resource stores configuration data as key-value pairs.
# The data provides the configurations for system components for the nginx-controller.
apiVersion: v1
kind: ConfigMap
data:
  log-format-upstream: '{"time_date": "$time_iso8601", "client": "$remote_addr",
                "host": "$http_host", "scheme": "$scheme",
                "request_method": "$request_method", "request_uri": "$uri",
                "request_id": "$request_id", "status": $status,
                "upstream_addr": "$upstream_addr", "upstream_status":
                $upstream_status, "request_time": $request_time,
                "upstream_response_time": $upstream_response_time,
                "upstream_connect_time": $upstream_connect_time,
                "upstream_header_time": $upstream_header_time}'
  log-format-escape-json: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liftr-gateway-web
  labels:
    app: liftr-gateway-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: liftr-gateway-web
  template:
    metadata:
      labels:
        app: liftr-gateway-web
        aadpodidbinding: liftr-aad-pod-identity
    spec:
      containers:
      - name: liftr-gateway-web-container
        image: {{ required "The imageRegistry parameter must be provided." .Values.imageRegistry }}/{{ required "The gatewayWeb.imageName parameter must be provided." .Values.gatewayWeb.imageName }}
        ports:
          - containerPort: 5000
        env:
          - name: STATSD_HOST
            value: geneva-services
          - name: VaultEndpoint
            value: {{ required "The Key Vault endpoint for the app to load secrets must be provided." .Values.vaultEndpoint }}
          - name: ASPNETCORE_ENVIRONMENT
            value: {{ required "The APP_ASPNETCORE_ENVIRONMENT must be provided." .Values.APP_ASPNETCORE_ENVIRONMENT }}
---
apiVersion: v1
kind: Service
metadata:
    name: "liftr-gateway-web-svc"
spec:
    ports:
        - port: 80
          protocol: TCP
          targetPort: 5000
    selector:
        app: liftr-gateway-web
    type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: liftr-gateway-web-ingress
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host:  {{ required "The hostname must be provided." .Values.hostname }}
      http:
          paths:
          - backend:
              serviceName: "liftr-gateway-web-svc"
              servicePort: 80
            path: /
  # This section is only required if TLS is to be enabled for the Ingress
  tls:
      - hosts:
          - {{ required "The hostname must be provided." .Values.hostname }}
        secretName: ingress-tls-secret