apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-gateway-web-svc
    namespace: {{ .Release.Namespace }}
    labels:
      app.kubernetes.io/managed-by: helm
spec:
    ports:
        - port: 80
          protocol: TCP
          targetPort: 5000
    selector:
        app: {{ .Release.Name }}-gateway-web
    type: ClusterIP